/* eslint-disable react/jsx-no-undef */
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/theme-provider'
import AppProvider from '@/app/AppProvider'
import './globals.css'
import { cookies } from 'next/headers'
import Header from '@/components/header/header'

const inter = Inter({ subsets: ['vietnamese'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = cookies()
  const accessToken = cookieStore.get('accessToken')
  const refreshToken = cookieStore.get('refreshToken')
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          <AppProvider initialAccessToken={accessToken?.value} initialRefreshToken={refreshToken?.value}>
            {children}
          </AppProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
